name: Automate EC2 Setup

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  automate-ec2:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    # 3. Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Run EC2 automation script
    - name: Execute EC2 Automation
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        python3 main.py
      continue-on-error: true  # This ensures the workflow doesn't stop on failure

    # 5. View log file
    - name: Upload logs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: automation-logs
        path: automation.log
      if: always()  # This ensures the log upload always happens, even if the previous steps fail  
